'\" t
.\"     Title: git-octopus
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/03/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GIT\-OCTOPUS" "1" "09/03/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-octopus \- extends \*(Aqgit merge\*(Aq with branch naming patterns\&.
.SH "SYNOPSIS"
.sp
.nf
\fIgit octopus\fR [\-n] [<pattern>\&...]
.fi
.SH "DESCRIPTION"
.sp
<pattern> can be any usual refspec or a naming pattern\&. Patterns are resolved using \fIgit ls\-remote\fR, the resulting refs are given to \fIgit merge\fR\&.
.sp
In case of conflicts, tries to reuse conflict resolutions stored by \fIgit conflict\fR in refs/conflicts/*\&. (See git\-conflict(1))\&.
.sp
In case of a merge failure, iterates over all the refs, computing merges with each ref (from HEAD) one by one for diagnosic purpose\&. Learn more about conflict management on the project\(cqs homepage
.SH "OPTIONS"
.PP
\-n
.RS 4
Leaves the repository back to HEAD\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Merge check of the current branch with all feature branches and the master from origin:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git octopus \-n origin/features/* origin/master
.fi
.if n \{\
.RE
.\}
.sp
This is basically a merge check you would do before pushing your branch\&.
.RE
.SH "CONFIGURATION"
.PP
octopus\&.commit
.RS 4
true by default\&. set to false behaves like \-n
.RE
.PP
octopus\&.pattern
.RS 4
Defines a branch naming pattern that
\fIgit octopus\fR
would use by default\&. Use multiple lines to define several patterns\&. See
git\-config(1)\&.
.RE
.SH "SEE ALSO"
.sp
git\-merge(1), git\-ls\-remote(1), git\-conflict(1)
